# Generated by Django 4.1.5 on 2023-01-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guild", "0002_alter_battle_enemy_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enemy",
            name="heroes",
        ),
        migrations.AddField(
            model_name="enemy",
            name="heroes",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enemy_hero",
                to="guild.heroes",
            ),
            preserve_default=False,
        ),
    ]
