# Generated by Django 4.1.5 on 2023-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guild", "0005_alter_enemy_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildmember",
            name="heroes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="guild_hero", to="guild.heroes"
            ),
        ),
    ]
