# Generated by Django 4.1.5 on 2023-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guild", "0006_alter_guildmember_heroes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildmember",
            name="heroes",
            field=models.ManyToManyField(related_name="guild_hero", to="guild.heroes"),
        ),
    ]
